### ISSUE TITLE
Is there a limit on how much data this extension can store on my computer because I don't want that limit ruin the value this extension provides me.

### ISSUE THREAD

**Issue by Harsh9425** [brianlinUM/youtube-timestamps#8]

**Comment by brianlinUM** [comment]
Hi Harsh! Thanks for your question :)

This extension uses the `storage.local` chrome API, which [by default](https://developer.chrome.com/docs/extensions/reference/api/storage#property-local) has a limit of 10MB. This _should_ be enough for most people - this extension really only stores text data in JSON format, so you'll need a pretty long video/timestamp list to actually reach the limit (I read somewhere like Lord of the Ring book series * 3 long).

If you do find yourself exceeding this limit (you'll probably get an error), then let me know and I can set probably set the extension to use the `unlimitedStorage` permission. I prefer not to though, since that would require another round of very long reviews from Google extension store's team.

**Comment by brianlinUM** [comment]
Of course, no guarantees to how safe that data is - if your notes and timestamps (or any data, really) are important, I would definitely recommend exporting and backing up your data.
